meta_name: "MoodMaestro"
meta_title: "MoodMaestro - Create personalised Spotify playlists"
meta_description: "Create the perfect playlist for every occasion"
meta_image: "cover.png" # should exist in `app/assets/images/`
